name: pf_refinement
dependencies:
    - python=2.7
    - pip
    - argparse
    - cycler
    - mpi4py
    - matplotlib
    - numpy
    - olefile
    - Pillow
    - pyparsing
    - python-dateutil
    - scipy
    - six
    - pytz
    - tqdm
    - pip:
            - mrcfile==0.2.10
            
