#!/usr/bin/env python
from pf_refinement import StarOp
from pf_refinement import gdGui

def getArgs():
    vals={
    'input_star_file': 'XXXSTARFILEXXX',
    'output_star_file': 'OUTPUT.star',
    'invert_polarity': False,
    'remove_symmetry': False
    }
    temp=gdGui('Preprocess Star File', **vals)
    params=temp.sendValues()
    return params
    
def procs(params):
    a=StarOp(params['input_star_file'])
    if params['remove_symmetry']:
        a.df=a.df.iloc[::a.num_pfs]
        
    if params['invert_polarity']:
        a.df.AnglePsi=(a.df.AnglePsi.astype(float)+180).astype(str)
    
    a.writeStar(params['output_star_file'])
    
if __name__ == "__main__":
    params=getArgs()
    procs(params)